// Package store defines core data types and the Store interface.
// Concrete SQLite implementation lives in internal/store/sqlite (or next to this file).
package store

import "time"

// Domain represents a news domain (e.g. "ai", "web3", "biotech").
// Day 1 only instantiates "ai".
type Domain struct {
	ID         string // 'ai', 'web3', ...
	Name       string // display name
	ConfigPath string // config/{id}.yaml
	CreatedAt  time.Time
}

// Source represents a concrete data source configuration
// (e.g. "GitHub Trending daily", "smol.ai RSS feed", "Folo list NEWS_AGGREGATOR").
type Source struct {
	ID         int64
	DomainID   string
	Type       string // 'github_trending' | 'rss' | 'folo_list' | ...
	Name       string
	ConfigJSON string // type-specific config (feed URL, list ID, auth, ...)
	// Category is parsed from ConfigJSON (SourceConfig.Category) when the
	// row is loaded. It is one of: news, blog, paper, project, community.
	// Used by classify to pre-bucket items via a deterministic rule before
	// asking the LLM for second-pass disambiguation of news → product_update
	// vs industry. Not persisted as its own column — the authoritative copy
	// lives in config/ai.yaml and is re-parsed on every ListEnabledSources
	// call.
	Category string
	// Priority 是 0-10 的整数, 从 ConfigJSON (SourceConfig.Priority) 解析出.
	// 用于 rank 阶段的加权评分 (v1.0.1 Phase 4.1): 同样 LLM 分数的两个 item,
	// priority 高的源(如 DeepMind / Google AI 设为 10)会排在 priority 低的
	// 源(无名博客设为 5)前面. 未设置 → 默认 5 (中性, 等同不加权).
	Priority  int
	Enabled   bool
	CreatedAt time.Time
}

// RawItem is a single item ingested from a Source, before any LLM processing.
type RawItem struct {
	ID           int64
	DomainID     string
	SourceID     int64
	ExternalID   string // source-side unique ID for dedup
	URL          string
	Title        string
	Author       string
	PublishedAt  time.Time // zero value allowed if unknown
	FetchedAt    time.Time
	Content      string // extracted body; may be empty on Day 1
	MetadataJSON string // arbitrary extra metadata
	// SignalStrength (v1.0.1 Phase 4.2) is the number of distinct source
	// hosts reporting the same story (fuzzy title match). 1 = single source,
	// ≥2 = cross-source corroboration ("hot story"). In-memory only — never
	// persisted, computed in-pipeline between filter/dedup and rank.
	SignalStrength int
	// CrossMentionCount (v1.0.1 Phase 4.6) 仅用于 opensource/project items
	// (来自 ossinsight): 该 repo 名在非 ossinsight 源的 title+content 中被
	// 提及的次数. 作为 rank prompt 的"圈内讨论热度"信号. In-memory only.
	CrossMentionCount int
}

// Issue represents a single daily briefing (one per domain per date).
type Issue struct {
	ID          int64
	DomainID    string
	IssueDate   time.Time  // only YYYY-MM-DD portion is meaningful
	IssueNumber int        // monotonic per-domain counter
	Title       string     // e.g. "2026年4月11日 AI洞察日报"
	Summary     string     // today's summary paragraph
	Status      string     // 'draft' | 'generated' | 'published'
	SourceCount int        // number of sources consulted
	ItemCount   int        // number of issue items
	GeneratedAt *time.Time // nil until generated
	PublishedAt *time.Time // nil until published
}

// IssueItem is one entry within an Issue, grouped into a named section.
type IssueItem struct {
	ID             int64
	IssueID        int64
	Section        string // 'product_update' | 'research' | 'industry' | 'opensource' | 'social'
	Seq            int    // order within section (1-based)
	Title          string
	BodyMD         string
	SourceURLsJSON string // JSON array of upstream URLs
	RawItemIDsJSON string // JSON array of contributing raw_items.id
	CreatedAt      time.Time
	// v1.0.1 per-section state tracking. Default 'validated' for rows
	// inserted by the pipeline on success. Stub rows start as 'pending',
	// failed sections become 'failed' without content, and regen of a
	// previously-validated item bumps RetryCount.
	Status      string
	ValidatedAt *time.Time
	RetryCount  int
}

// IssueInsight captures the cross-item "industry insight" and "our takeaways"
// generated by the LLM for an Issue.
type IssueInsight struct {
	ID          int64
	IssueID     int64
	IndustryMD  string // 3-4 行业洞察 bullets (markdown)
	OurMD       string // 2-3 对我们的启发 bullets (markdown)
	Model       string // e.g. "gpt-5.4"
	Temperature float64
	RetryCount  int // how many repair attempts were needed
	GeneratedAt time.Time
	// v1.0.1 per-stage state tracking. Status tracks the insight LLM
	// call itself; InfocardStatus tracks the visual card render stage,
	// which can degrade independently (e.g. insight text is validated
	// but card PNGs failed to render).
	Status         string
	ValidatedAt    *time.Time
	InfocardStatus string
}

// WeeklyIssue represents a weekly summary report aggregating daily Issues.
type WeeklyIssue struct {
	ID                  int64
	DomainID            string
	Year                int
	Week                int       // ISO 8601 week number
	StartDate           time.Time // Monday
	EndDate             time.Time // Sunday
	Title               string
	FocusMD             string // 本周聚焦
	SignalsMD           string // 信号与噪音
	TrendsMD            string // 宏观趋势
	TrendsDiagram       string // Mermaid simple diagram for trends
	TrendsDiagramDetail string // Mermaid detailed diagram for trends
	TakeawaysMD         string // 对我们的启发
	PonderMD            string // 本周思考
	FullMD              string // rendered full markdown
	DailyIssueIDs       string // JSON array of daily issue IDs
	Status              string
	GeneratedAt         *time.Time
	PublishedAt         *time.Time
}

// Delivery records an attempt to publish an Issue to a specific channel.
type Delivery struct {
	ID           int64
	IssueID      int64
	Channel      string // 'slack_test' | 'slack_prod' | 'feishu_doc' | 'feishu_bot'
	Target       string // webhook URL / doc token / chat_id
	Status       string // 'sent' | 'failed' | 'skipped'
	ResponseJSON string // raw response body or error message
	SentAt       time.Time
}

// Section name constants used by compose/render to categorize items.
const (
	SectionProductUpdate = "product_update"
	SectionResearch      = "research"
	SectionIndustry      = "industry"
	SectionOpenSource    = "opensource"
	SectionSocial        = "social"
)

// Issue status constants.
const (
	IssueStatusDraft     = "draft"
	IssueStatusGenerated = "generated"
	IssueStatusPublished = "published"
)

// Delivery status constants.
const (
	DeliveryStatusSent    = "sent"
	DeliveryStatusFailed  = "failed"
	DeliveryStatusSkipped = "skipped"
)

// Channel name constants.
const (
	ChannelSlackTest = "slack_test"
	ChannelSlackProd = "slack_prod"
	ChannelFeishuDoc = "feishu_doc"
	ChannelFeishuBot = "feishu_bot"
)

// Per-section / per-stage status constants (v1.0.1 critical fix).
//
// The progression is: pending -> running -> {validated, degraded, failed}.
//
//	pending   — row exists but no attempt yet (stub from InsertStubIssueItems)
//	running   — worker holds it; if crashed, RecoverStaleRunningStages flips
//	            it to 'failed'
//	validated — content is real, non-empty, passed every validator
//	degraded  — content exists but a secondary validator warned (e.g.
//	            missing mermaid diagram); currently only used for images
//	failed    — attempt completed but content is missing/invalid; DO NOT
//	            render to prod
const (
	SectionStatusPending   = "pending"
	SectionStatusRunning   = "running"
	SectionStatusValidated = "validated"
	SectionStatusDegraded  = "degraded"
	SectionStatusFailed    = "failed"
)

// Pipeline stage status constants (issue_stages.status).
const (
	StageStatusRunning   = "running"
	StageStatusSucceeded = "succeeded"
	StageStatusFailed    = "failed"
	StageStatusSkipped   = "skipped"
)

// Canonical pipeline stage names used in issue_stages.stage. Kept here
// so run.go, status.go, and repair.go agree on spelling.
const (
	StageIngest   = "ingest"
	StageFilter   = "filter"
	StageRank     = "rank"
	StageClassify = "classify"
	StageCompose  = "compose"
	StageMedia    = "media"
	StageInsight  = "insight"
	StageSummary  = "summary"
	StageInfocard = "infocard"
	StageRender   = "render"
	StageGate     = "gate"
	StagePublish  = "publish"
)

// Delivery sub-status values (used by deliveries.sub_status UNIQUE
// constraint to distinguish test vs prod vs alert publish on the same
// channel).
const (
	DeliverySubStatusTest  = "test_pub"
	DeliverySubStatusProd  = "prod_pub"
	DeliverySubStatusAlert = "alert_pub"
)

// ClassifiedItem is the persisted output of the classify stage. One
// row per (issue, section, raw_item). Introduced in v1.0.1 so
// `briefing repair --section X` can re-run compose for a single
// section without paying the LLM cost of a full classify round.
type ClassifiedItem struct {
	ID        int64
	IssueID   int64
	Section   string // one of SectionProductUpdate .. SectionSocial
	RawItemID int64
	RankScore float64 // 0..1 from the rank stage; pass-through
	Seq       int     // order within section as produced by classify
	CreatedAt time.Time
}

// IssueStage records one execution of one pipeline stage for one
// issue. A re-run of the same stage appends a new row with an
// incremented Version, so history is preserved.
type IssueStage struct {
	ID             int64
	IssueID        int64
	Stage          string // one of StageIngest..StagePublish
	Status         string // one of StageStatus*
	InputHash      string // sha256 over normalized input JSON (may be empty)
	Version        int    // 1-based; monotonic per (issue, stage)
	ParentVersions string // JSON array of parent stage versions this call depended on
	StartedAt      time.Time
	CompletedAt    *time.Time
	ErrorText      string
}

// LLMCall is one row in the llm_calls audit log. Written once per LLM
// request (success or failure) so postmortems can reconstruct exactly
// what models were hit when and with what latency.
type LLMCall struct {
	ID             int64
	IssueID        *int64 // nullable: some early-stage calls have no issue yet
	Stage          string // one of StageCompose/StageInsight/StageSummary/...
	Model          string
	PromptHash     string // sha256 of the prompt body (for reproducibility)
	RequestTokens  int
	ResponseTokens int
	LatencyMS      int
	HTTPStatus     int    // 200 on success, actual upstream code on failure
	ErrorText      string // empty on success
	CalledAt       time.Time
}

// SourceHealth tracks per-source ingest outcome. v1.0.1 Phase 1.3.
// One row per source, upserted on every ingestAll run so operators can
// surface staleness / consecutive failures / auto-disable candidates.
type SourceHealth struct {
	SourceID            int64
	LastSuccessAt       *time.Time
	LastErrorAt         *time.Time
	ConsecutiveFailures int
	LastErrorText       string
	LastItemCount       int
	AutoDisabled        bool
	UpdatedAt           time.Time
}
