name: Test Dispatch

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:
    inputs:
      run_date:
        description: "Test date"
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Dispatch works!"
